#ifndef GLIMPL_H
#define GLIMPL_H


#define IMPL_MAX_MODELVIEW_STACK_DEPTH	32
#define IMPL_MAX_PROJECTION_STACK_DEPTH	2
#define IMPL_MAX_TEXTURE_STACK_DEPTH	2
#define IMPL_MAX_TEXTURE_SIZE			1024


#endif
